### ISSUE TITLE
feature-toggle-jsx: New HOC that will decorate the child with selected features as props.

### ISSUE THREAD

**Issue by matmalkowski** [matmalkowski/react-handyman#142]
**Is your feature request related to a problem? Please describe.**
Right now only way to access features and configuration is with `useFeature(s)` hook. Unfortunetly, not always component is a functional one, and you cannot use hook. We need another way of injecting defined features into the components than hook alone.

**Describe the solution you'd like**
Clean and simple solution would be cusom higher order component that would be basically 

```
connectWithFeatures(Component, ['some feature'])
``` 

that would extend the props of children with selected features/configuration

**Describe alternatives you've considered**
Render prop is only other way, but I don't think it might be nice here.

**Additional context**

**Comment by peawyoyoyin** [comment]
is this closed? if not I can add this feature

**Comment by matmalkowski** [comment]
@peawyoyoyin I think this pr: #402 might be solving this issue with existing API, can you take a look?

**Comment by peawyoyoyin** [comment]
It did fulfill the requirement.

**Comment by matmalkowski** [comment]
Great, will close this since #402 implements it
